### ISSUE TITLE
No Menu Items/Not working on 5.8?

### ISSUE THREAD

**Issue by sleewok** [civicrm/org.civicrm.tutorial#3]
CiviCRM 5.8
Drupal 7
Shoreditch Theme

We do not have a "Support" menu so no menu items are showing. I renamed our "Help" menu to "Support" and re-installed the extension. The menu still does not show anything about the tutorial. The tutorial does not show when viewing a contact for the first time. Tutorial.js is loading, but I'm not seeing any errors so I am unsure of where to look. Any thoughts?

**Comment by colemanw** [comment]
This extension goes by name not label when looking for that menu. Every CiviCRM install has, by default, a menu item with the name "Support" - if yours is missing one, try changing the name of your help menu to "Support" in the database. You can keep the label set to anything you want.

**Comment by sleewok** [comment]
That worked. Thanks!
