### ISSUE TITLE
Cannot read property 'administer CiviCRM' of undefined

### ISSUE THREAD

**Issue by andyburnsco** [civicrm/org.civicrm.tutorial#5]
Using WP 4.9. and Civi 5.8.2 on multisite.

For users who are not admins I get this error. When trying to click on the civi menu it produces the error. The menu does not respond. 
![capture](https://user-images.githubusercontent.com/18341942/51946715-0da7db00-23e8-11e9-88c8-137768bb9d38.PNG)

![capture](https://user-images.githubusercontent.com/18341942/51946754-244e3200-23e8-11e9-8457-e89f93204c1c.PNG)

**Comment by colemanw** [comment]
@andyburnsco thanks for posting this. Have a look at the fix above ^

**Comment by andyburnsco** [comment]
I applied the patch and see

- The menu at the bottom of screen
- Sometimes it does not even load
- Logged in a non-admin and menu does not respect permissions (I see all nav options).

**Comment by andyburnsco** [comment]
![capture](https://user-images.githubusercontent.com/18341942/51997359-32e62900-247c-11e9-8338-c0e0cfc6e3c9.PNG)

**Comment by andyburnsco** [comment]
![capture](https://user-images.githubusercontent.com/18341942/51997411-4b564380-247c-11e9-8f15-b05e0f4eedac.PNG)

**Comment by andyburnsco** [comment]
![capture](https://user-images.githubusercontent.com/18341942/51997482-704ab680-247c-11e9-840f-60eb1394e9f8.PNG)

**Comment by colemanw** [comment]
@andyburnsco what version of this extension are you using? Note that the latest version requires the KAM extension.

**Comment by andyburnsco** [comment]
KAM is installed and 1.1 for CiviTutorial.

**Comment by colemanw** [comment]
@andyburnsco something's not right - the KAM menu should be grey but the one in your screenshot is black. Are you sure you've got the latest version of KAM installed?

**Comment by andyburnsco** [comment]
![capture](https://user-images.githubusercontent.com/18341942/52067030-558d4600-253f-11e9-8f3d-10eec4a2302c.PNG)

It's black because CiviCRM Admin Utilities WP plugin is styling it. KAM 1.0 installed.

**Comment by colemanw** [comment]
Hmm. The error you posted in https://github.com/civicrm/org.civicrm.tutorial/issues/5#issuecomment-459017938 doesn't make much sense to me but if you want me to log into your site and poke around PM me.
