### ISSUE TITLE
Access Denied on Make It Happen link

### ISSUE THREAD

**Issue by joemcl** [civicrm/org.civicrm.tutorial#9]
I get `ACCESS DENIED You are not authorized to access this page.` when clicking on the Make It Happen link in readme doc.

**Comment by mlutfy** [comment]
Thanks @joemcl - I removed the MIH link because when MIH campaigns are over, we unpublish the page (related issue here: https://lab.civicrm.org/marketing/civicrm-website/-/issues/213)
